### ISSUE TITLE
Python3.7.7 运行的时候报错，并且项目里没有main2.py这个文件

### ISSUE THREAD

**Issue by GangYe293** [ying-ck/fanqienovel-downloader#109]
![fanqie](https://github.com/user-attachments/assets/9a08fbba-29b7-42c3-8f44-f19705b69541)

错误日志如下：
D:\软件安装包\fanqienovel-downloader-main\src>python server.py
Traceback (most recent call last):
  File "server.py", line 5, in <module>
    from flask_socketio import SocketIO, emit
  File "C:\Users\wangj\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 52, in <module>
    class SocketIO:
  File "C:\Users\wangj\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 168, in SocketIO
    reason = socketio.Server.reason
AttributeError: type object 'Server' has no attribute 'reason'

D:\软件安装包\fanqienovel-downloader-main\src>

希望大佬可以帮忙看看，谢谢了

**Comment by sunnysab** [comment]
可以使用更新版本的 python 吗？我这边 python3.12、3.13 正常

**Comment by GangYe293** [comment]
> 可以使用更新版本的 python 吗？我这边 python3.12、3.13 正常

可以试试，可为什么项目里没有main2.py啊
