### ISSUE TITLE
1.0.7 和 1.0.9 的区别问题

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#18]
作者你好！
我在相同的电脑环境下，使用1.0.7下载一部小说完全正常
![1 0 7](https://github.com/user-attachments/assets/997bd89a-5923-400e-a168-dd74df240732)

而当换成1.0.9时却直接报错
![1 0 9](https://github.com/user-attachments/assets/1e7e728e-827f-43ce-b20d-fb12965fcc99)

分析问题1：两个版本在不同的文件夹中，不会互相影响。
分析问题2：猜测可能是因为开了全局代理。关闭后1.0.9可以正常运行，但不明白为什么1.0.7可以正常运行而1.0.9却不行。盼处理，再次感谢！

**Comment by qxqycb** [comment]
请问你下载的是哪个版本？

**Comment by qxqycb** [comment]
有可能你下载的是v1.0.9的旧版本，请在releases下载新的版本

**Comment by doggybread** [comment]
我下载的是这个版本：
![B0](https://github.com/user-attachments/assets/530b2200-ef16-4acd-983a-f70bb1121216)

**Comment by doggybread** [comment]
我把CMD中的运行结果贴在下面：

【1、开全局代理的情况】

Microsoft Windows [版本 10.0.19045.4780]
(c) Microsoft Corporation。保留所有权利。

C:\Fanqie-Novel-Download\1.0.9>fanqienovel-downloader-v1.0.9.exe
本程序完全免费。
Github: https://github.com/ying-ck/fanqienovel-downloader
作者：Yck & qxqycb

输入书的id直接下载
输入下面的数字进入其他功能:

1. 更新小说
2. 搜索
3. 批量下载
4. 设置
5. 退出

1
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 777, in urlopen
  File "urllib3\connectionpool.py", line 1046, in _prepare_proxy
  File "urllib3\connection.py", line 619, in connect
  File "urllib3\connection.py", line 692, in _connect_tls_proxy
  File "urllib3\connection.py", line 793, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 471, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 515, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
OSError: [Errno 0] Error

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError(0, 'Error'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 497, in send
  File "urllib3\connectionpool.py", line 846, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fanqienovel.com', port=443): Max retries exceeded with url: /page/7383253525251230782 (Caused by ProxyError('Unable to connect to proxy', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fanqienovel-downloader-v1.0.9.py", line 269, in <module>
  File "fanqienovel-downloader-v1.0.9.py", line 80, in down_book
  File "fanqienovel-downloader-v1.0.9.py", line 18, in down_zj
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='fanqienovel.com', port=443): Max retries exceeded with url: /page/7383253525251230782 (Caused by ProxyError('Unable to connect to proxy', OSError(0, 'Error')))
[10148] Failed to execute script 'fanqienovel-downloader-v1.0.9' due to unhandled exception!


【2、关闭全局代理的情况】

C:\Fanqie-Novel-Download\1.0.9>fanqienovel-downloader-v1.0.9.exe
本程序完全免费。
Github: https://github.com/ying-ck/fanqienovel-downloader
作者：Yck & qxqycb

输入书的id直接下载
输入下面的数字进入其他功能:

1. 更新小说
2. 搜索
3. 批量下载
4. 设置
5. 退出

1

开始下载《1级1个金词条，说我召唤师弱？》，状态‘连载中’
下载 第113章 千变万化！可惜你我的差距更大了！
下载 第114章 魔王-鳌！不愧是龟壳！
100%|████████████████████████████████████████████████████████████████████████████████| 114/114 [00:01<00:00, 85.86it/s]
更新完成

输入书的id直接下载
输入下面的数字进入其他功能:

1. 更新小说
2. 搜索
3. 批量下载
4. 设置
5. 退出

**Comment by doggybread** [comment]
奇怪的是，在相同的环境下，即使开了全局代理，1.0.7也能够正常运行。

**Comment by ying-ck** [comment]
可能是因为打包时Python环境不同，可以考虑使用别的代理方式，如使用规则或自动代理

**Comment by doggybread** [comment]
嗯，这个不是什么很严重的问题，只要把全局代理关掉就行了。
