### ISSUE TITLE
下载的json文件怎么导入到微信图书

### ISSUE THREAD

**Issue by 204065248** [ying-ck/fanqienovel-downloader#23]
rt, 我用epub就会报错

```bash
本程序完全免费。
Github: https://github.com/ying-ck/fanqienovel-downloader
作者：Yck & qxqycb
正在获取cookie
成功

输入书的id直接下载
输入下面的数字进入其他功能:

1. 更新小说
2. 搜索
3. 批量下载
4. 设置
5. 退出

4
请选择项目：1.正文段首占位符 2.章节下载间隔延迟 3.小说保存路径 4.小说保存方式
4
请选择：1.保存为单个 txt 2.分章保存 3.保存为 epub 4.保存为 HTML 网页格式 5.保存为 LaTeX
3
设置完成

输入书的id直接下载
输入下面的数字进入其他功能:

1. 更新小说
2. 搜索
3. 批量下载
4. 设置
5. 退出

2
请输入搜索关键词（直接Enter返回）：神帝奶爸
1. 名称：神帝奶爸 作者：拾光笔默 ID：7072513635255323683 字数：2458693
2. 名称：战神奶爸 作者：方寸山 ID：6795361988357655565 字数：3053121
3. 名称：绝品仙尊奶爸 作者：莽 ID：7012888463972240387 字数：4570344
4. 名称：仙帝奶爸在都市 作者：多龙 ID：6918012994802682888 字数：4637349
5. 名称：无上神帝 作者：蜗牛狂奔 ID：6543443058099227662 字数：15564403
6. 名称：青辰神帝 作者：一匹青瓦 ID：7031075557903174659 字数：1835425
7. 名称：仙帝归来：把老婆女儿宠上天 作者：唯爱然宝 ID：7297948639769398312 字数：284639
8. 名称：仙帝归来当奶爸 作者：黄金蛮牛 ID：6776680229311089672 字数：4384167
9. 名称：长生归来当奶爸 作者：平放 ID：6750703466034760717 字数：3732802
10. 名称：九界神帝 作者：神月 ID：6968675206931942430 字数：3802397
请选择一个结果, 输入 r 以重新搜索：1

开始下载《神帝奶爸》，状态‘已完结’
Traceback (most recent call last):
  File "fanqienovel-downloader-fast-v1.1.3.py", line 674, in <module>
  File "fanqienovel-downloader-fast-v1.1.3.py", line 524, in book2down
  File "fanqienovel-downloader-fast-v1.1.3.py", line 194, in down_book_epub
NameError: name 'tqdm' is not defined
[26128] Failed to execute script 'fanqienovel-downloader-fast-v1.1.3' due to unhandled exception!
```

**Comment by qxqycb** [comment]
感谢你的反馈，这个错误会在一周之内修改

**Comment by yan-qy** [comment]
在修改出来之前，请使用另一个版本

**Comment by qxqycb** [comment]
修改完成，请下载最新版本
