### ISSUE TITLE
web版启动报错闪退

### ISSUE THREAD

**Issue by shanyan-wcx** [ying-ck/fanqienovel-downloader#97]
BASE_DIR: C:\Users\ADMINI~1\AppData\Local\Temp\_MEI445322
DATA_ROOT: E:\fanqie-web
DATA_DIR: E:\fanqie-web\data
BOOKSTORE_DIR: E:\fanqie-web\data\bookstore
DOWNLOADS_DIR: E:\fanqie-web\novel_downloads
INFO:__main__:
────────────────────────────────────────────────
│                                                  │
│   番茄小说下载器 Web 服务已启动                      │
│                                                  │
│   请在浏览器中访问:                                 │
│   http://localhost:12930                         │
│                                                  │
│   如果需要从其他设备访问，请使用:                     │
│   http://<本机IP>:12930                           │
│                                                  │
╰──────────────────────────────────────────────────╯

Traceback (most recent call last):
  File "gevent\threadpool.py", line 173, in __run_task
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 0: invalid continuation byte
2024-11-25T00:45:56Z (<ThreadPoolWorker at 0x1e86a337080 thread_ident=0xa9ec threadpool-hub=<Hub at 0x1e8697946d0 thread_ident=0x2840>>, <built-in function gethostbyaddr>) failed with UnicodeDecodeError

Traceback (most recent call last):
  File "server.py", line 1112, in <module>
  File "flask_socketio\__init__.py", line 729, in run
  File "gevent\baseserver.py", line 398, in serve_forever
  File "gevent\baseserver.py", line 336, in start
  File "gevent\pywsgi.py", line 1669, in init_socket
  File "gevent\pywsgi.py", line 1681, in update_environ
  File "gevent\_socketcommon.py", line 286, in getfqdn
  File "gevent\_socketcommon.py", line 252, in gethostbyaddr
  File "gevent\resolver\thread.py", line 66, in gethostbyaddr
  File "gevent\pool.py", line 161, in apply
  File "src\\gevent\\event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "gevent\_compat.py", line 49, in reraise
  File "gevent\threadpool.py", line 173, in __run_task
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 0: invalid continuation byte
[5400] Failed to execute script 'server' due to unhandled exception!

**Comment by baiheyyds** [comment]
这个一般是计算机主机名带有中文导致的，
1、cmd输入“hostname”看看返回的是不是“我的电脑”这种名字，
2、如果是的话，按 Win + R，输入 sysdm.cpl 打开 系统属性。
3、点击 计算机名 标签，然后点击 更改。
4、将主机名更改为仅包含英文和数字的字符串。
